project:
  type: "website"
  title: "CRE | Chemical Reaction Engineering"
  output-dir: _site
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!ideas/"
    - "!_env/"
    - "!renv/"
    - "!certificate*"
  resources:
    - "resources/"
  preview:
    port: 4200
    browser: true
  # This also renders during preview...
  # post-render: node ./convert-to-pdf.js

description-meta: "An undergraduate course on chemical reaction engineering."

# Course library
bibliography: ./bibliography/library.bib
csl: ./bibliography/chicago-author-date.csl
link-citations: true
link-bibliography: true

execute:
  warning: true
  echo: false
  freeze: auto
  enabled: true
  execute-dir: project

website:
  title: "CRE | Chemical Reaction Engineering"
  site-url: https://cre.smilelab.dev/
  page-navigation: true
  open-graph: true
  # cookie-consent: true
  favicon: ./assets/images/logo/favicon.png
  search:
    type:
      overlay
      # location: navbar
      # type: textbox
  navbar:
    background: primary
    logo: ./assets/images/logo/smile-lab-logo-dark-bg.png
    logo-alt: "Smile lab logo."
    title: false
    left:
      # - text: Research
      #   href: https://smilelab.dev/research/
      - text: Publications
        href: https://smilelab.dev/publications/
      - text: Teaching
        href: https://smilelab.dev/teaching/
      - text: People
        href: https://smilelab.dev/people/
      - text: Blog
        href: https://smilelab.dev/blog/
  page-footer:
    border: false
    background: "#535353"
    left: |
      Copyright 2024 &copy; [SMILE Lab](https://www.smilelab.dev) <br>
    right: |
      {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}
      {{< fa brands creative-commons-sa >}} Except where otherwise noted,
      content on this site <br>is licensed under a [Creative Commons CC BY-NC
      4.0)](https://creativecommons.org/licenses/by-nc/4.0/)

  sidebar:
    style: docked
    collapse-level: 2
    background: "#f4f4f4"
    contents:
      - file: index.qmd
        text: "{{< fa house >}} Home"
      - section: "Overview"
        contents:
          - file: content/info/index.qmd
          - file: content/info/syllabus.qmd
            text: Syllabus

      - section: "Lectures"
        id: lectures
        contents:
          - file: ./content/lectures/01-mole-balances/index.qmd
          - file: ./content/lectures/02-conversion-and-reactor-sizing/index.qmd
          - file: ./content/lectures/03-rate-law-and-stoichiometry/index.qmd
          - file: ./content/lectures/04-isothermal-reactor-design/index.qmd
          - file: ./content/lectures/05-collection-and-analysis-of-rate-data/index.qmd
          - file: ./content/lectures/06-multiple-reactions/index.qmd
          - file: ./content/lectures/07-non-isothermal-reactor-design/index.qmd
          - file: ./content/lectures/08-reaction-mechanisms-and-catalysis/index.qmd
          - file: ./content/lectures/11-distribution-of-residence-time/index.qmd
          #
      - section: "Workshops"
        id: workshops
        contents:
          - file: ./content/workshops/index.qmd
          - file: ./content/workshops/01-mole-balances/index.qmd
            text: Mole balances
          - file: ./content/workshops/02-conversion-and-reactor-sizing/index.qmd
            text: Conversion and reactor sizing
          - file: ./content/workshops/03-rate-law-and-stoichiometry/index.qmd
            text: Rate law and stoichiometry
          - file: ./content/workshops/04-isothermal-reactor-design/index.qmd
            text: Isothermal reactor design
          - file: ./content/workshops/05-collection-and-analysis-of-rate-data/index.qmd
            text: Collection and analysis of rate data
          - file: ./content/workshops/06-multiple-reactions/index.qmd
            text: Multiple reactions
          - file: ./content/workshops/07-non-isothermal-reactor-design/index.qmd
            text: Non-isothermal reactor design
          - file: ./content/workshops/08-reaction-mechanisms-and-catalysis/index.qmd
            text: Reaction mechanisms and catalysis
          - file: ./content/workshops/11-distribution-of-residence-time/index.qmd
            text: Distribution of residence times
      #
      - section: "Labs"
        id: labs
        contents:
          - file: ./content/labs/Experiment-01-Batch-Saponification-Reaction-of-EtAc-and-NaOH/index.qmd
            text: Experiment 1
          - file: ./content/labs/Experiment-02-Reaction-rate-constant-using-a-tubular-reactor/index.qmd
            text: Experiment 2
          - file: ./content/labs/Experiment-03-Study-of-Sucrose-Inversion/index.qmd
            text: Experiment 3
          - file: ./content/labs/Experiment-04-Effect-of-throughput-on-conversion-using-tubular-reactor/index.qmd
            text: Experiment 4
          - file: ./content/labs/Experiment-05-Determination-of-the-residence-time-in-a-CSTR/index.qmd
            text: Experiment 5
      #
      - section: "Portfolio"
        id: portfolio
        contents:
          - file: ./content/portfolio/01-mole-balances/index.qmd
            text: Mole balances
          - file: ./content/portfolio/02-conversion-and-reactor-sizing/index.qmd
            text: Conversion and reactor sizing
          - file: ./content/portfolio/03-isothermal-reactor-design/index.qmd
            text: Isothermal reactor design
          - file: ./content/portfolio/04-analysis-of-rate-data/index.qmd
            text: Analysis of rate data
          - file: ./content/portfolio/05-multiple-reactions/index.qmd
            text: Multiple reactions
      #
format:
  html:
    theme:
      light:
        - ./assets/styles/carbon_light.scss
    toc: true
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:[a-zA-Z0-9-]+\.)?smilelab\.dev\/|localhost
    include-after-body: ./assets/helpers/goatcounter.html
