---
title: "Portfolio 03: Non-isothermal reactor design"
format:
  pdf
date-modified: 2025-05-15 
---
<!-- ::: {.content-visible when-format="html"} -->
<!---->
<!-- ::: {.callout-note} -->
<!-- ## Solutions -->
<!---->
<!-- Answers to the portfolio questions are uploaded at [Portfolio 2 answers](./portfolio-02-answers.qmd) -->
<!---->
<!-- ::: -->
<!---->
<!-- ::: -->
<!---->

::: {.content-visible when-format="pdf"}

## Student ID: 

## General Instructions for take home Portfolios

1.  The portfolio is an open-book task.
2.  It is expected that you will complete the portfolio assessment on your own.
    You can use textbooks, the resources provided during class/ workshop etc.
    to answer the questions. 
4.  You are free to choose a solution technique. It is **not** required that
    you use the provided python code to answer the questions. You can use any
    tool (pen and paper, excel, ... ) and any technique (graphical, numerical,
    analytical) that you are comfortable with. However, some of the tasks will
    require use of coding/ computer. 
5.  The tasks will be a mix of theory questions, short calculation type and
    long numerical examples.
6.  The portfolio tasks are not meant to take a lot of time. If you have
    understood and practiced the relevant content, it should take you around 2
    to 3 hours at the most.
7.  You are required to upload the portfolio answers on to blackboard: 
    - Save your report as a **pdf** file (_Miri students should save it as a
      word file_). 
    - Rename the file as STUDENTID_Portfolio_x.pdf (Where STUDENTID is your
      student ID, and x is the portfolio number) and 
    - Upload it using assessment submission link on blackboard. 

## Academic Integrity

Academic integrity at its core is about honesty and responsibility and is
fundamental to Curtin’s expectations of you. This means that all of your work
at Curtin should be your own and it should be underpinned by integrity, which
means to act ethically, honestly and with fairness.

As a Curtin student you are part of an academic community and you are asked to
uphold the University’s [Code of
Conduct](https://oasis.curtin.edu.au/ConductAtCurtin), principles of academic
integrity, and [Curtin’s five core
values](https://about.curtin.edu.au/who/vision-mission-values/curtin-values/)
of integrity, respect, courage, excellence and impact during your studies.

You are also expected to uphold the [Student
Charter](https://students.curtin.edu.au/essentials/rights/student-charter/) and
recognise that cheating, plagiarism collusion, and falsification of data and
other forms of academic dishonesty are not acceptable.

For more information, visit
[https://students.curtin.edu.au/essentials/rights/academic-integrity/](https://students.curtin.edu.au/essentials/rights/academic-integrity/)

{{< pagebreak >}}
$~$
{{< pagebreak >}}

:::

```{python}
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import pandas as pd
import tabulate as tab
from IPython.display import display, Markdown
plt.style.use('../../../assets/templates/publish.mplstyle')
```

```{python}
# Data
v0_total = 100.0     # m^3/min
ca0 = 2        # mol/ m^3
n_tubes = 100 
d_tube = 10 # cm
l_tube = 10 # m

T0 = 571  # K, reactor inlet temp
T_c0 = 320  # K, coolant inlet temp

k1 = 10.0  # m^3/mol min
k2 = 5.0   # m^3/mol^0.2 min
k3 = 2.0   # 1/min

# Heat of reactions (J/mol)
dH1 = -50000
dH2 = -30000
dHD = 25000

# Thermophysical properties
Cp = 150      # J/mol·K (reacting fluid)
rho_c = 1000  # kg/m³
Cp_c = 4180   # J/kg·K (coolant)
U = 100       # W/m²·K

# Reactor parameters
v0_total = 100    # m^3/min
ca0 = 2              # mol/m^3
n_tubes = 25
l_tube = 10          # m

# Coolant flow rate (kg/min)
m_dot_c = 3.2 

# Experimental data
t1  = 270
data_270 = {
    "Time (min)": [0.0, 0.5, 1.0, 2.0, 3.0, 4.0],
    "$C_{A}$ (mol/m³)": [2.0, 0.132057, 0.060176, 0.018847, 0.007220, 0.003646],
    "$C_{D}$ (mol/m³)": [0.000000, 0.484713, 0.313037, 0.114116, 0.047501, 0.017765]
}

t2 = 230
data_230 = {
    "Time (min)": [0, 2, 4, 6, 8, 10, 12, 15],
    "$C_{A}$ (mol/m³)": [2.0, 0.1424, 0.0630, 0.0356, 0.0212, 0.0146, 0.0107, 0.0068],
    "$C_{D}$ (mol/m³)": [0.0000, 0.4449, 0.2524, 0.1334, 0.0692, 0.0370, 0.0191, 0.0071]
}

df_230 = pd.DataFrame(data_230)
df_270 = pd.DataFrame(data_270)

```

A specialty chemicals manufacturer produces a high-value intermediate D from
feedstock A through a multi-reaction system.

The following reactions occur in the process:

$$
\begin{aligned}
\text{desired reaction: }      &\quad \ce{2A -> D} &\qquad -r_{1A} &= k_1 C_A^2 \\
\text{undesired reaction: }    &\quad \ce{A -> U1} &\qquad -r_{2A} &= k_2 C_A^{1.2} \\
\text{undesired degradation: } &\quad \ce{D -> U2} &\qquad -r_{D}  &= k_3 C_D
\end{aligned}
$$

## Question 1: Reaction kinetics \hfill (20 marks)

Experiments were performed in an isothermal batch reactor at two temperatures:
230°C and 270°C. Initial concentration of A was `{python} f'{ca0}'` mol/m^3^.

The experimental concentration profiles of A and D obtained are given below:

```{python}
#| label: tbl-exp230
#| tbl-cap: Concentration profiles of $C_A$ and $C_D$ at 230 °C.

# Create and format DataFrame
df = pd.DataFrame(data_230)
df["Time (min)"] = df["Time (min)"].map(lambda x: f"{x:.1f}")
df["$C_{A}$ (mol/m³)"] = df["$C_{A}$ (mol/m³)"].map(lambda x: f"{x:.4f}")
df["$C_{D}$ (mol/m³)"] = df["$C_{D}$ (mol/m³)"].map(lambda x: f"{x:.4f}")

md = tab.tabulate(df.T)
display(Markdown(md))

```

```{python}
#| label: tbl-exp270
#| tbl-cap: Concentration profiles of $C_A$ and $C_D$ at 270 °C.

df = pd.DataFrame(data_270)
df["Time (min)"] = df["Time (min)"].map(lambda x: f"{x:.1f}")
df["$C_{A}$ (mol/m³)"] = df["$C_{A}$ (mol/m³)"].map(lambda x: f"{x:.4f}")
df["$C_{D}$ (mol/m³)"] = df["$C_{D}$ (mol/m³)"].map(lambda x: f"{x:.4f}")

md = tab.tabulate(df.T)
display(Markdown(md))

```
(a) Using the rate laws and appropriate numerical methods do the following:

  - Write the mole balance equations for species A and D in a batch reactor. \hfill (4 marks)
  - Define the objective function used for estimate the kinetic parameters from
  experimental data. \hfill (4 marks)
  - Estimate the values of k~1~, k~2~, k~3~ for both temperatures (i.e., using
  both datasets), and compare model predictions with the experimental data
  using appropriate plots. \hfill (6 marks)

(b) Calculate the activation energies $E_1$, $E_2$, and $E_3$ and the
corresponding pre-exponential factors $k_{0,1}, k_{0,2}, k_{0,3}$ using the
rate constants obtained in part (a). \hfill (6 marks)


{{< pagebreak >}}

## Question 2: Non-isothermal reactor design \hfill (20 marks)

The current manufacturing facility uses a shell-and-tube tubular reactor
comprising 100 parallel tubes. The reactor is operated isobarically and
near-isothermal operations are maintained using external cooling. 

The reactor is operated at constant pressure under non-isothermal steady-state
conditions. The reaction mixture flows through the tubes, and a cooling fluid
flows co-currently on the shell side to maintain thermal control.

Each tube has a diameter of `{python} f'{d_tube}'`cm and a length of 
`{python} f'{l_tube}'` m. The total volumetric flow rate of the feed is
`{python} f'{v0_total}'` m³/min, and the inlet concentration of A is 
`{python} f'{ca0}'` mol/m³. Values of other necessary parameters are given in
@tbl-q2. 


| Parameter                      | Value             |
| ------------------------------ | ----------------- |
| Reactor temperature            | `{python} f'{T0}'` K             |
| Inlet reactant temperature     | `{python} f'{T0}'` K             |
| Inlet coolant temperature        | `{python} f'{T_c0}'` K             |
| Coolant flow rate        | `{python} f'{m_dot_c}'` kg/min             |
| $\Delta H_{1A}$ (for A → D)    | `{python} f'{dH1}'` J/mol   |
| $\Delta H_{2A}$ (for A → U1)   | `{python} f'{dH2}'` J/mol   |
| $\Delta H_{D}$ (for D → U2)    | `{python} f'{dHD}'` J/mol |
| Heat capacity of fluid, $C_p$ | `{python} f'{Cp}'` $J/mol \cdot K$      |
| Heat capacity of coolant, $C_{p,c}$ |  `{python} f'{Cp_c}'` $J/kg \cdot K$ | 
| Coolant density                        | `{python} f'{rho_c}'` $kg/m^3$        |
| Heat transfer coefficient $U$  | `{python} f'{U}'` $W/m^2 \cdot K$        |

: Additional information for question 2 {#tbl-q2}

(a) Write mass balances for all species in the reactor and energy
balances for both the reacting fluid and the coolant. Define all terms and
assumptions used. Assume constant physical properties and perfect radial
mixing. \hfill (12 marks)

(b) Using the provided skeleton code, calculate the conversion of A and the
    yield of D under the current coolant flow rate.

  - What is the Conversion of A, and Yield of D \hfill (4 marks)
  - What would be the Conversion of A, and Yield of D if the coolant flow rate
    was increased to 4 kg/min? Provide a small discussion on the impact of
    increasing coolant flow rate on Conversion and Yield. \hfill (4 marks)

{{< pagebreak >}}

## Question 3: Reaction mechanism \hfill (10 marks)

The main reaction $\ce{2A -> D}$ has been observed to follow the empirical rate
law $-r_{1A} = k_1 C_A^2$. 

Propose a plausible multi-step reaction mechanism for this overall reaction.
Your mechanism must include at least one active intermediate species.

Apply the Pseudo-Steady-State Hypothesis (PSSH) to the active intermediate(s)
in your proposed mechanism. Using the result from the PSSH, derive the rate law
for the disappearance of reactant A ($-r_{1A}$) based on your mechanism.
Finally, demonstrate how your derived rate law matches the given empirical rate
law under the appropriate limiting conditions. Clearly defining the overall
rate constant $k_1$ in terms of the rate constants of your proposed elementary
steps.


