---
title: Getting Ready
date-modified: 2024-05-10
---

## Pre-requisites

- CHEN2000 (v.0) Mass and Energy Balances or any previous version
- CHEN2001 (v.0) Thermodynamics or any previous version 

### Excel

We will use excel for calculations and data analysis

- Here is a good introductory series on using Excel for engineering
  applications. [Excel Training for
  Engineers](https://www.youtube.com/playlist?list=PLUQP7hTI4zC8-7mTTotSiNt1hma7irN_M).

### Python and Jupyter notebook

We will also use python (and Jupyter notebooks) for computationally demanding
tasks (such as solving ordinary differential equations). Course specific
instructions will be provided as we go along. There are several options for
using Jupyter notebooks. Here are a few pointers for using Jupyter notebooks. 

- [Python Programming And Numerical Methods: A Guide For Engineers And
  Scientists](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html)
- [Jupyter Notebook Tutorial for Beginners with
  Python](https://www.youtube.com/watch?v=2WL-XTl2QYI)
- [Jupyter Notebook Complete Beginner Guide - From Jupyter to Jupyterlab,
  Google Colab and Kaggle!](https://www.youtube.com/watch?v=5pf0_bpNbkw) 
- [Get started with Jupyter Notebooks in less than 4 minutes](https://www.youtube.com/watch?v=h1sAzPojKMg)
- [Jupyter Notebooks in VS Code Walkthrough](https://www.youtube.com/watch?v=DA6ZAHBPF1U)

## Attendance and participation

It is essential to complete the required pre class activities for each class
session **prior to** watching the lecture.

Your active participation and preparedness in class, is essential before you
come to the class every week. **This includes having read the material and watched
the videos**. This will enable you to engage in discussions and collaborate with
your peers.

Attendance and participation will play a vital role in your success in this
course. All the activities are designed for in-person classes, and
unfortunately, some of the activities in the lectures, workshops, or labs will
not be recorded. If you anticipate missing a session, you will need to
apply for extension and complete the lab work in your own time later. 

That said, I am here to support you in your learning. If by any chance you are
going through any issues that may have an impact on your participation in the
unit (e.g. attending a session, sitting for test, completing project etc.),
inform me at the earliest and I will do my best to accomodate your
requirements.



